services:

  h2db:
    image: oscarfonts/h2
    container_name: supernova-h2

    ports:
      - "1521:1521"
      - "81:81"

    volumes:
      - ./data:/opt/h2-data

    networks:
      - supernova-net

  app:
    build: .
    container_name: supernova-api

    ports:
      - "8080:8080"

    depends_on:
      - h2db

    restart: always

    networks:
      - supernova-net

networks:
  supernova-net: